// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oixdelrweyqmwwnzmrga.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9peGRlbHJ3ZXlxbXd3bnptcmdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI2MzgwMjUsImV4cCI6MjA4ODIxNDAyNX0.LlAs0eDe_WfwFHPl9n83Q6kuNgeZkF6G7NX9D4sX4gk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});